services:
  python-server:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./python-server/src:/app/src
  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - ./express-server:/app
      - express_node_modules:/app/node_modules

volumes:
  express_node_modules:
